---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_reges: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python


- name: Install python3, docker and docker-compose
  hosts: all
  become: yes
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name:
          - docker
          - docker-compose

- name: Create new Linux User
  hosts: all
  become: yes
  tasks:
    - name: Create new linux user
      user:
        name: docker-user
        groups: adm,docker

- name: Start docker container
  hosts: all
  become: yes
  become_user: docker-user
  vars_prompt:
    - name: docker_password
      prompt: Enter password for docker registry
  tasks:
    - name: Copy Docker Compose
      copy:
        src: ./docker-compose.yml
        dest: /home/docker-user/docker-compose.yml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: garstiops
        password: "{{docker_password}}"
    - name: Start containers from compose
      docker_compose:
        project_src: /home/docker-user
